# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180407_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitlyurl',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
